In [10]:
import numpy as np
x=np.array([[25,2],[5,26],[3,7]])
y=np.array([[2,2],[5,24],[0,7]])
x*y

array([[ 50,   4],
       [ 25, 624],
       [  0,  49]])

In [12]:
import torch
X_pt=torch.tensor([[25,2],[5,26],[3,7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [13]:
import tensorflow as tf
X_tf=tf.Variable([[25,2],[5,26],[3,7]])
X_tf


<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]])>

In [14]:
import tensorflow as tf
X_tf=tf.Variable([[25,2],[5,26],[3,7]])
tf.transpose(X_tf)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[25,  5,  3],
       [ 2, 26,  7]])>

In [21]:
import numpy as np
a=np.array([[4,2],[-2,7]])
b=np.array([8,11])
x=np.linalg.solve (a,b)
x

array([1.0625, 1.875 ])

In [23]:
import torch
a=torch.tensor([[4,2],[-2,7]])
b=torch.tensor([8,11])
x=torch.linalg.solve(a,b)
x

RuntimeError: linalg.solve: Expected a floating point or complex tensor as input. Got Long