In [19]:
import numpy as np
import random
y=[]
for i in range(0,11):
    x=random.randint(0,10)
    y.append(x)

a=np.array([[y[1],y[2],y[3]],
            [y[4],y[5],y[6]],
            [y[7],y[8],y[9]]])

z=[]
for i in range(0,11):
    x=random.randint(0,10)
    z.append(x)

b=np.array([[z[1],z[2],z[3]],
            [z[4],z[5],z[6]],
            [z[7],z[8],z[9]]])



print('矩陣A為',a,sep='\n')
print('矩陣B為',b,sep='\n')
print('矩陣A+B為',a+b,sep='\n')
print('矩陣A-B為',a-b,sep='\n')
print('矩陣A*B為',a*b,sep='\n')
print('A的轉置矩陣為',a.transpose(),sep='\n')





矩陣A為
[[9 2 1]
 [4 9 7]
 [6 3 5]]
矩陣B為
[[ 2  3 10]
 [ 9  4  2]
 [ 1  3  2]]
矩陣A+B為
[[11  5 11]
 [13 13  9]
 [ 7  6  7]]
矩陣A-B為
[[ 7 -1 -9]
 [-5  5  5]
 [ 5  0  3]]
矩陣A*B為
[[18  6 10]
 [36 36 14]
 [ 6  9 10]]
A的轉置矩陣為
[[9 4 6]
 [2 9 3]
 [1 7 5]]
