In [33]:
import numpy as np
A = np.array([[-1,2], [3,-2], [5,7]])
print('A\n', A)

A
 [[-1  2]
 [ 3 -2]
 [ 5  7]]


In [34]:
U, D, VT = np.linalg.svd( A )
print('U\n', U)
print('D\n', D)
print('VT\n', VT)

U
 [[ 0.12708324  0.47409506  0.87125411]
 [ 0.00164602 -0.87847553  0.47778451]
 [ 0.99189069 -0.0592843  -0.11241989]]
D
 [8.66918448 4.10429538]
VT
 [[ 0.55798885  0.82984845]
 [-0.82984845  0.55798885]]


In [35]:
D_Plus = np.linalg.inv(np.diag(D))
D_Plus = np.concatenate((D_Plus,
                         np.array([[0,0]]).T),
                         axis = 1).T
print('D+\n', D_Plus)

D+
 [[0.1153511  0.        ]
 [0.         0.24364718]
 [0.         0.        ]]


In [36]:
A_Plus = np.dot(U, np.dot(D_Plus, VT)).T
print('A_Plus\n', A_Plus)

A_Plus
 [[-0.08767773  0.17772512  0.07582938]
 [ 0.07661927 -0.1192733   0.08688784]]


In [37]:
print(np.dot(A_Plus, A))

[[ 1.00000000e+00 -1.94289029e-16]
 [-9.71445147e-17  1.00000000e+00]]


In [38]:
print('A\n', A )
print('Moore Penrose Pseudoinverse of A\n',
      np.linalg.pinv( A ))

A
 [[-1  2]
 [ 3 -2]
 [ 5  7]]
Moore Penrose Pseudoinverse of A
 [[-0.08767773  0.17772512  0.07582938]
 [ 0.07661927 -0.1192733   0.08688784]]


In [39]:
import torch
A = torch.tensor([[-1,2],[3,-2],[5,7.]])
A

tensor([[-1.,  2.],
        [ 3., -2.],
        [ 5.,  7.]])

In [40]:
A_plus = torch.pinverse( A )
A_plus

tensor([[-0.0877,  0.1777,  0.0758],
        [ 0.0766, -0.1193,  0.0869]])