In [2]:
import numpy as np
a=np.array([[6,-5,2],[2,1,-4],[3,-3,1]])
b=np.array([3,5, -1])

x=np.linalg.solve(a, b)
x=np.array([round(x[0]),round(x[1]),round(x[2])])
x

array([4, 5, 2])

In [3]:
import numpy as np
a=np.array([[2,-5,3],[3,-1,4],[1,3,2]])
b=np.array([8,7,-3])
x=np.linalg.solve(a,b)
x=[round(x[0]),round(x[1]),round(x[2])]
x=np.array([round(x[0]),round(x[1]),round(x[2])])
x

array([ 6, -1, -3])

In [4]:
import numpy as np
a=np.array([[5,-3,2],[2,-1,-1],[3,-2,2]])
b=np.array([-5,4,-7])
x=np.linalg.solve(a,b)
x=np.array([round(x[0]),round(x[1]),round(x[2])])
x

array([ 7, 12, -2])

In [5]:
import numpy as np
a=np.array([[4,-3,3],[1,2,-1],[-2,-1,3]])
b=np.array([-1,2,-4])
x=np.linalg.solve(a,b)
x

array([ 0.59375,  0.28125, -0.84375])

In [7]:
try:
    import numpy as np
    a=np.array([[1,-1,2],[2,1,-2],[4,-1,2]])
    b=np.array([3,1,0])
    x=np.linalg.solve(a,b)
    x=np.array([round(x[0]),round(x[1]),round(x[2])])
    x

except:
    print('矩陣不存在逆矩陣')

矩陣不存在逆矩陣
