In [1]:
import numpy as np
A = np.array([[4, 2],
            [-5, -3]])
A


array([[ 4,  2],
       [-5, -3]])

In [2]:
lambdas, V = np.linalg.eig(A)
V_inv = np.linalg.inv(V)
print(lambdas)
print(V)
print(V_inv)


[ 2. -1.]
[[ 0.70710678 -0.37139068]
 [-0.70710678  0.92847669]]
[[2.3570226  0.94280904]
 [1.79505494 1.79505494]]


In [3]:
Lambda = np.dot(np.dot(V_inv, A), V)
Lambda


array([[ 2.00000000e+00,  2.33636299e-16],
       [ 2.26818301e-17, -1.00000000e+00]])

In [4]:
A2 = np.dot(A, A)
A2

array([[ 6,  2],
       [-5, -1]])

In [5]:
A2_1 = np.dot(np.dot(V, Lambda**2),V_inv)
A2_1

array([[ 6.,  2.],
       [-5., -1.]])